"""Add username to users and title to todos

Revision ID: ac3338455ae2
Revises: 
Create Date: 2025-08-24 01:02:22.897827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac3338455ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add username column as nullable first
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    
    # Update existing users with a default username based on their email
    op.execute("UPDATE users SET username = SUBSTRING_INDEX(email, '@', 1) WHERE username IS NULL")
    
    # Now make username not nullable and add unique index
    op.alter_column('users', 'username', 
                   existing_type=sa.String(length=255),
                   nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Add title column to todos as nullable first
    op.add_column('todos', sa.Column('title', sa.String(length=255), nullable=True))
    
    # Update existing todos with a default title based on description
    op.execute("UPDATE todos SET title = SUBSTRING(description, 1, 50) WHERE title IS NULL")
    
    # Now make title not nullable
    op.alter_column('todos', 'title',
                   existing_type=sa.String(length=255),
                   nullable=False)
    
    # Make description nullable
    op.alter_column('todos', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.alter_column('todos', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###